# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SynthDataset": "01_synth_dataset.ipynb",
         "gen_values": "01_synth_dataset.ipynb",
         "gen_added_n_deleted": "01_synth_dataset.ipynb",
         "exclude_element": "01_synth_dataset.ipynb",
         "build_interactions": "01_synth_dataset.ipynb",
         "build_features_from_df": "01_synth_dataset.ipynb",
         "SynthDataset.build_synth_dataset": "01_synth_dataset.ipynb"}

modules = ["synth.py"]

doc_url = "https://sgaseretto.github.io/lfmu/"

git_url = "https://github.com/sgaseretto/lfmu/tree/master/"

def custom_doc_links(name): return None
